@startuml

/' diagram meta data start
config=CallConfiguration;
{
  "rootMethod": "ch.heig.dai.lab.SMTP.CmdHandler#run()",
  "projectClassification": {
    "searchMode": "OpenProject", // OpenProject, AllProjects
    "includedProjects": "",
    "pathEndKeywords": "*.impl",
    "isClientPath": "",
    "isClientName": "",
    "isTestPath": "",
    "isTestName": "",
    "isMappingPath": "",
    "isMappingName": "",
    "isDataAccessPath": "",
    "isDataAccessName": "",
    "isDataStructurePath": "",
    "isDataStructureName": "",
    "isInterfaceStructuresPath": "",
    "isInterfaceStructuresName": "",
    "isEntryPointPath": "",
    "isEntryPointName": "",
    "treatFinalFieldsAsMandatory": false
  },
  "graphRestriction": {
    "classPackageExcludeFilter": "",
    "classPackageIncludeFilter": "ch.heig.dai.lab.SMTP",
    "classNameExcludeFilter": "",
    "classNameIncludeFilter": "*",
    "methodNameExcludeFilter": "",
    "methodNameIncludeFilter": "",
    "removeByInheritance": "", // inheritance/annotation based filtering is done in a second step
    "removeByAnnotation": "",
    "removeByClassPackage": "", // cleanup the graph after inheritance/annotation based filtering is done
    "removeByClassName": "",
    "cutMappings": false,
    "cutEnum": true,
    "cutTests": true,
    "cutClient": true,
    "cutDataAccess": true,
    "cutInterfaceStructures": true,
    "cutDataStructures": true,
    "cutGetterAndSetter": true,
    "cutConstructors": true
  },
  "graphTraversal": {
    "forwardDepth": 3,
    "backwardDepth": 3,
    "classPackageExcludeFilter": "",
    "classPackageIncludeFilter": "",
    "classNameExcludeFilter": "",
    "classNameIncludeFilter": "*",
    "methodNameExcludeFilter": "",
    "methodNameIncludeFilter": "",
    "hideMappings": false,
    "hideDataStructures": false,
    "hidePrivateMethods": true,
    "hideInterfaceCalls": true, // indirection: implementation -> interface (is hidden) -> implementation
    "onlyShowApplicationEntryPoints": false, // root node is included
    "useMethodCallsForStructureDiagram": "ForwardOnly" // ForwardOnly, BothDirections, No
  },
  "details": {
    "aggregation": "GroupByClass", // ByClass, GroupByClass, None
    "showMethodParametersTypes": false,
    "showMethodParametersNames": false,
    "showMethodReturnType": false,
    "showPackageLevels": 2,
    "showCallOrder": false,
    "edgeMode": "MethodsOnly", // TypesOnly, MethodsOnly, TypesAndMethods, MethodsAndDirectTypeUsage
    "showDetailedClassStructure": false
  },
  "rootClass": "ch.heig.dai.lab.SMTP.CmdHandler",
  "extensionCallbackMethod": "" // qualified.class.name#methodName - signature: public static String method(String)
}
diagram meta data end '/



digraph g {
    rankdir="LR"
    splines=polyline
    

'nodes 
subgraph cluster_3198683 { 
   	label=heig
	labeljust=l
	fillcolor="#ececec"
	style=filled
   
   subgraph cluster_885107207 { 
   	label=dai
	labeljust=l
	fillcolor="#d8d8d8"
	style=filled
   
   subgraph cluster_1041738286 { 
   	label=MailAddress
	labeljust=l
	fillcolor=white
	style=filled
   
   MailAddress1745489629XXXgetFrom104431[
	label="+ getFrom()"
	style=filled
	fillcolor=white
	tooltip="MailAddress

null"
	fontcolor=darkgreen
];

MailAddress1745489629XXXgetTo104431[
	label="+ getTo()"
	style=filled
	fillcolor=white
	tooltip="MailAddress

null"
	fontcolor=darkgreen
];
} 

subgraph cluster_1057484375 { 
   	label=MailContent
	labeljust=l
	fillcolor=white
	style=filled
   
   MailContent1745489629XXXgetContent104431[
	label="+ getContent()"
	style=filled
	fillcolor=white
	tooltip="MailContent

null"
	fontcolor=darkgreen
];

MailContent1745489629XXXgetSubject104431[
	label="+ getSubject()"
	style=filled
	fillcolor=white
	tooltip="MailContent

null"
	fontcolor=darkgreen
];
} 

subgraph cluster_1126615434 { 
   	label=MainTest
	labeljust=l
	fillcolor=white
	style=filled
   
   MainTest1745489629XXXmain1859653459[
	label="+ main()"
	style=filled
	fillcolor=white
	tooltip="MainTest

null"
	fontcolor=darkgreen
];
} 

subgraph cluster_1999602053 { 
   	label=CmdHandler
	labeljust=l
	fillcolor=white
	style=filled
   
   CmdHandler1745489629XXXclearScreen0[
	label="+ clearScreen()"
	style=filled
	fillcolor=white
	tooltip="CmdHandler

null"
	fontcolor=darkgreen
];

CmdHandler1745489629XXXrun0[
	label="+ run()"
	style=filled
	fillcolor=white
	tooltip="CmdHandler

null"
	penwidth=4
	fontcolor=darkgreen
];
} 

subgraph cluster_94145121 { 
   	label=ConnectionHandler
	labeljust=l
	fillcolor=white
	style=filled
   
   ConnectionHandler1745489629XXXrun0[
	label="+ run()"
	style=filled
	fillcolor=white
	tooltip="ConnectionHandler

null"
	fontcolor=darkgreen
];
} 
} 
} 

'edges    
CmdHandler1745489629XXXrun0 -> CmdHandler1745489629XXXclearScreen0;
CmdHandler1745489629XXXrun0 -> ConnectionHandler1745489629XXXrun0;
CmdHandler1745489629XXXrun0 -> MailAddress1745489629XXXgetFrom104431;
CmdHandler1745489629XXXrun0 -> MailAddress1745489629XXXgetTo104431;
CmdHandler1745489629XXXrun0 -> MailContent1745489629XXXgetContent104431;
CmdHandler1745489629XXXrun0 -> MailContent1745489629XXXgetSubject104431;
ConnectionHandler1745489629XXXrun0 -> MailAddress1745489629XXXgetFrom104431;
ConnectionHandler1745489629XXXrun0 -> MailAddress1745489629XXXgetTo104431;
ConnectionHandler1745489629XXXrun0 -> MailContent1745489629XXXgetContent104431;
ConnectionHandler1745489629XXXrun0 -> MailContent1745489629XXXgetSubject104431;
MainTest1745489629XXXmain1859653459 -> CmdHandler1745489629XXXrun0;
    
}
@enduml